### PR TITLE
Use relative path to erbb from max module to configure and build

### LINKED ISSUE #544: bash: erbb: command not found on Max
After following the [documentation](https://eurorack-blocks.readthedocs.io/en/latest/max/setup.html) to setup `erbb`, I'm unable to build the [`Reverb.maxpat`](https://github.com/ohmtech-rdi/eurorack-blocks/blob/main/max/reverb/Reverb.maxpat) example.

The `erb.build.js` fails with the following error:

```
...
node.script: Build starting
node.script: Error: bash: erbb: command not found
node.script: Error: bash: erbb: command not found
node.script: child process exited with code 127
```

It seems that Max can't find the path to `erbb`.

A possible solution would be to execute the `erbb` commands by giving either an absolute or relative path to the `erbb` file.

### PR DESCRIPTION
**Pull request by eliottparis**
This PR fixes #544 by using relative path to erbb from max module to configure and build in `erb.build.js` script.

### CODE REVIEW

**Review by ohmtech-rdi — APPROVED** [review]
Great fix! LGTM 👍

**Comment by ohmtech-rdi** [comment]
@OmsInSerial Could you please give this fix a try?
It modifies the way we build from inside of Max. The idea for you to test would be to load one of your Max patch, save, and see if any errors pop-up in the Max console. Thanks!

**Comment by ohmtech-rdi** [comment]
Report from @OmsInSerial (report has been tempered to obfuscate name)

```
node.script: artifacts already exists, skipping.
param: Param osc2_depth_cv_in_plugged has no minimum; default to using min=0.
param: Param osc2_depth_cv_in_plugged has no maximum; default to using max=1.
param: Param index_cv_in_plugged has no minimum; default to using min=0.
param: Param index_cv_in_plugged has no maximum; default to using max=1.
param: Param mix_cv_in_plugged has no minimum; default to using min=0.
param: Param mix_cv_in_plugged has no maximum; default to using max=1.
param: Param audio_in1_plugged has no minimum; default to using min=0.
param: Param audio_in1_plugged has no maximum; default to using max=1.
param: Param osc1_depth_cv_in_plugged has no minimum; default to using min=0.
param: Param osc1_depth_cv_in_plugged has no maximum; default to using max=1.
param: Param audio_in2_plugged has no minimum; default to using min=0.
param: Param audio_in2_plugged has no maximum; default to using max=1.
param: Param osc1_ratio_cv_in_plugged has no minimum; default to using min=0.
param: Param osc1_ratio_cv_in_plugged has no maximum; default to using max=1.
param: Param osc2_ratio_cv_in_plugged has no minimum; default to using min=0.
param: Param osc2_ratio_cv_in_plugged has no maximum; default to using max=1.
gen~: exported: Macintosh HD:/Users/***/Documents/projects/OmsInSerial/FMEinheit/artifacts/module_max.cpp
node.script: Build starting
node.script: module: /Users/***/Documents/projects/OmsInSerial/FMEinheit/
node.script: Configuring...
node.script: Error: /Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/***/Documents/projects/OmsInSerial/FMEinheit/../../build-system/scripts/erbb': [Errno 2] No such file or directory
node.script: child process exited with code 2
node.script: Building...
node.script: Error: /Applications/Xcode.app/Contents/Developer/usr/bin/python3: can't open file '/Users/***/Documents/projects/OmsInSerial/FMEinheit/../../build-system/scripts/erbb': [Errno 2] No such file or directory
node.script: child process exited with code 2
```
Capture d’écran 2023-06-09 à 10 53 15

**Review by ohmtech-rdi — CHANGES_REQUESTED** [review]
Apparently, problem with search paths. I think what happened is that the test project happened to match the relative path to erbb. @eliottparis

**Comment by eliottparis** [comment]
@OmsInSerial Thanks for testing 🙏!
@ohmtech-rdi I think you are right, my bad!

I made a fixup that should resolve that.  

As the `Eurorack-blocks` Max package is just an alias created with 
`~/eurorack-blocks/max$ ln -s "$(pwd)/Eurorack-blocks" ~/Documents/Max\ 8/Packages/Eurorack-blocks` as stated in the documentation, the path to `erbb` is now crafted from the `erb.build.js` script _dirname_.

> Note: @OmsInSerial With that modification, I think there is no need to have `Errb`: `[...]/eurorack-blocks/build-system` in the search paths.

What do you both think?

**Comment by ohmtech-rdi** [comment]
> the path to erbb is now crafted from the erb.build.js script dirname.

On this, I think we should take the same approach as we do in Python:
- If possible use a function to get the parent directory rather than using `..` (I can totally feel that could break on some platforms)
- Make something in the end that is an absolute path, and ensure it is that way

> With that modification, I think there is no need to have Errb: [...]/eurorack-blocks/build-system in the search paths

I think it's still needed when loading a user patch, so that the user patch can find the eurorack-blocks patch? (inside Max)

**Comment by OmsInSerial** [comment]
@eliottparis

```
git pull
Updating fd8e0fa..bd2aef2
Fast-forward
 max/Eurorack-blocks/javascript/erb.build.js | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)
``` 

Then

``` 
node.script: artifacts already exists, skipping.
gen~: exported: Macintosh HD:/Users/christophecornu/Documents/projects/OmsInSerial/Boardtest/artifacts/module_max.cpp
node.script: Build starting
node.script: module: /Users/christophecornu/Documents/projects/OmsInSerial/Boardtest/
node.script: Configuring...
node.script: child process exited with code 0
node.script: Building...
node.script: ACTION Max
node.script: ACTION UI
node.script: ACTION VCV Rack
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/rogan.6ps.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/rogan.5ps.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/rogan.3ps.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/rogan.2ps.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/rogan.2s.black.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/rogan.1ps.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/rogan.1s.black.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/rogan.1s.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/sifam.dbn151.white.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/sifam.drn111.white.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/songhuei.9mm.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/thonk.pj398sm.knurled.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/dailywell.2ms.1.svg
COPY eurorack-blocks/include/erb/vcvrack/resource/thonk.pj398sm.hex.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/dailywell.2ms.2.svg
node.script: COPY eurorack-blocks/include/erb/vcvrack/resource/dailywell.2ms.3.svg
node.script: CXX eurorack-blocks/src/Button.cpp
node.script: CXX eurorack-blocks/src/GateOut.cpp
CXX eurorack-blocks/src/detail/Debounce.cpp
node.script: CXX eurorack-blocks/src/detail/Animation.cpp
CXX eurorack-blocks/src/detail/Sdram.cpp
node.script: CXX eurorack-blocks/src/detail/Sram.cpp
node.script: CXX eurorack-blocks/src/vcvrack/BoardGeneric.cpp
node.script: CXX eurorack-blocks/include/gen_dsp/genlib.cpp
node.script: CXX plugin_vcvrack.cpp
node.script: CXX Boardtest_erbb.cpp
node.script: CXX Boardtest_erbui.cpp
node.script: CXX module_max_alt.cpp
node.script: LINK plugin.dylib
node.script: PACKAGE Release Boardtest
node.script: INSTALL /Users/christophecornu/Documents/Rack2/plugins/Boardtest/
node.script: child process exited with code 0
```


So it seems the soft link resolves the issue!

**Review by ohmtech-rdi — COMMENTED** [review]
Seems better to me like that. I think you can rebase and squash the fixups now 👍

**Comment by eliottparis** [comment]
> Actually, isn't this mandatory to make sure that MAX can find the eurorack-blocks patch?

As `Eurorack-blocks` is in Max Packages directory, it will be added to the Max search path automatically, so the patch and resources will be found.

**Comment by ohmtech-rdi** [comment]
> As `Eurorack-blocks` is in Max Packages directory, it will be added to the Max search path automatically, so the patch and resources will be found.

Ah right, so in the documentation:
```console
~/eurorack-blocks$ cd max
~/eurorack-blocks/max$ ln -s "$(pwd)/Eurorack-blocks" ~/Documents/Max\ 8/Packages/Eurorack-blocks
```
That's what make it work, right?

**Comment by eliottparis** [comment]
> That's what make it work, right?

Yes exactly

**Review by ohmtech-rdi — APPROVED** [review]
LGTM 👍

**Pull request merged**
